version: 2.0
jobs:
  create_testenv:
    machine: true
    steps:
      - checkout
    # login to docker:
      - run:
          name: Build and Push Test Env Image to DockerHub 
          command: |
                   echo "Publishing new image with build num $CIRCLE_BUILD_NUM"
                   docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t vintherwolf/001-unityc-prjt:$CIRCLE_BUILD_NUM -t vintherwolf/001-unityc-prjt:latest .
      - run: docker push vintherwolf/001-unityc-prjt:$CIRCLE_BUILD_NUM
      - run: docker push vintherwolf/001-unityc-prjt:latest
  Build_and_Test:
    docker:
      - image: vintherwolf/001-unityc-prjt:latest
    steps:
      - checkout
      - run:
          name: Compile Files
          command: make
      - run: 
          name: Unit Tests
          command: ./Test_DumbExample.out              
      - store_artifacts:
          path: /code/test-results
          destination: prefix
  wrap_up:
    docker:
      - image: vintherwolf/001-unityc-prjt:latest
    steps:
      - checkout
      - run:
          command: echo "All done"

workflows:
  version: 2
  jobSequence:
    jobs:
      - create_testenv:
          filters:
            branches:
              only: master
            tags:
              only: /D.*/
      - build_and_test:
          requires:
            - create_testenv
      - wrap_up:
          filters:
            branches:
              only: 
                - master
          requires:
            - create_testenv
            - build_and_test
