version: 2.0
jobs:
  create-testenv:
    machine: true
    steps:
      - checkout
    # login to docker:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    #build the image
      - run: docker build -t vintherwolf/001_unityc_prjt:$CIRCLE_SHA1 .

    # deploy the image 
      - run: docker push vintherwolf/001_unityc_prjt:$CIRCLE_SHA1
  compile:
    docker:
      - image: vintherwolf/001_unityc_prjt:latest
    steps:
      - checkout
      - run:
          command: |
                    make
                    ./Test_DumbExample.out
      - store_artifacts:
          path: /code/test-results
          destination: prefix
  unit-test:
    docker:
      - image: vintherwolf/001_unityc_prjt:latest
    steps:
      - checkout
      - run:
          command: |
                    make
                    ./Test_DumbExample.out
      - store_artifacts:
          path: /code/test-results
          destination: prefix

workflows:
  version: 2
  jobSequence:
    jobs:
      - create-testenv:
          filters:
            branches:
              only:
                - master
      - compile:
          requires:
            - create-testenv
      - unit-test:
          filters:
            branches:
              only: 
                - master
          requires:
            - create-testenv
            - compile
